### ISSUE TITLE
Question: How are you guys importing static assets into main.ts?

### ISSUE THREAD

**Issue by mikeliao97** [saucesteals/electron-typescript-react-webpack-tailwind-redux#14]
Thanks for the boilerplate!

I am trying to create a tray with icon, but the image is not showing up. Any help would be appreciated :)

**I see that in `main.ts` there is a line of code but I don't think it works because the icon is electron and not react.**
```
    icon: path.join(
      __dirname,
      "..",
      "assets",
      "package",
      "icons",
      "png",
      "1024x1024.png"
    )
```

**What I'm trying to do**
``` 
  let trayPath =  path.join(
    "..",
    "assets",
    "package",
    "icons",
    "png",
    "32x32.png"
  )
  let trayIcon = nativeImage.createFromPath(trayPath);
  console.log('isempty', trayIcon.isEmpty()); // prints true
  tray = new Tray(trayIcon)
```

**What I am trying**
additional webpack config. 
https://gist.github.com/bbudd/2a246a718b7757584950b4ed98109115

webpack noob here, why does this mean?
```
  {
    test: /\.(png|svg|jpg|jpeg|gif|woff|woff2|eot|ttf|otf)$/i,
    type: "asset",
    generator: {
      filename: "assets/[hash][ext]",
    },
    parser: {
      dataUrlCondition: {
        maxSize: 4 * 1024, // 4 KB
      },
    },
  }
 ```

**Comment by saucesteals** [comment]
I've went ahead and removed the `icon` option from the window since you don't really need it anyways because it can just use the executable icon (it was a little broken since I didn't take webpack's loading into account) 

Im guessing by tray u mean the the macos dock/windows taskbar since you want to fix the electron icon thats already shown 
From what I've tried you cant really replace the icon in dev, but it does work perfectly fine if you launch a packaged version (if you've properly set the icon in the forge config)

If you mean the actual tray, Im not quite sure as to why it would show the electron icon since it doesnt even have that fallback, if you pass in a bad image path it will just hang and not print the `console.log('isempty', trayIcon.isEmpty()); // prints true` you mentioned
